# In a land shrouded in mystery...

cyber_name := Dark Cyber
construction_year := 1100
destruction_year := 1678

duration := $(shell echo $$(($(destruction_year) - $(construction_year))))

all:
    @echo "The duration of $(cyber_name) was $(duration) years."

# ...there stood a Dark Cyber
